site_name: Nhập môn Khoa học dữ liệu
site_description: Introduction to Data Science
site_author: Hung Nguyen

repo_url: https://github.com/nd-hung/datascience
edit_uri: tree/main/docs

nav:
    - Các chủ đề:
      - Tổng quan về khoa học dữ liệu: topics\overview\README.md
      - Lập trình xử lý dữ liệu với Python: topics\#
      - Thu thập và tiền xử lý dữ liệu: topics\#
      - Phân tích khám phá dữ liệu: topics\#
      - Các mô hình phân tích dữ liệu: topics\#
      - Ứng dụng học máy trong khoa học dữ liệu: topics\#
      - Các bài thực hành: labs\README.md

    - Giảng viên: author\about.md 

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
        - content.action.view

extra_css:
  - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - def_list
    - tables
